export { default as Discord } from './discord'
export { default as Email } from './email'
export { default as Github } from './github'
export { default as LinkedIn } from './linkedin'
export { default as WhatsApp } from './whats-app'